/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javaatlas.Views.GeneralInformationAboutEarth;

import com.mycompany.javaatlas.MainForm;
import com.mycompany.javaatlas.Views.GeneralInformationView;

/**
 *
 * @author user
 */
public class FeaturesOfTheEarthsRotationView extends javax.swing.JFrame {
    private String _address;
    
    /**
     * Creates new form FeaturesOfTheEarthsRotationView
     */
    public FeaturesOfTheEarthsRotationView() {
        _address = new MainForm().getAddress();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        content1Scroll = new javax.swing.JScrollPane();
        content1 = new javax.swing.JTextArea();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        content2Scroll = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        title.setText("Особливості обертання Землі");

        content1.setColumns(20);
        content1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        content1.setRows(5);
        content1.setText(" Повне обертання навколо Сонця Земля робить за 365,3 доби, а навколо своєї осі\nза 23 години 56 хвилин.\nШвидкість осьового обертання з часом сповільнюється.\nУ початковий період існування планети вона була в кілька разів більшою.");
        content1Scroll.setViewportView(content1);

        icon1.setIcon(new javax.swing.ImageIcon(_address + "Images/FeaturesOfTheEarthsRotation1.png"));
        icon1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        icon2.setIcon(new javax.swing.ImageIcon(_address + "Images/FeaturesOfTheEarthsRotation2.jpg"));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Точки, які розташовані на екваторі, протягом однієї доби роблять повне обертання і проходять відстань 40075 км, тобто рухаються\nз лінійною швидкістю 460 м/с.\nНа широті України така швидкість складає відповідно близько 300 м/с, а у напрямку до полюсів вона поступово зменшується до\nнульових величин.\n\nВісь обертання Землі нахилена до площини її орбіти під кутом близько 66˚, що визначає зміну пір року в північній і південній півкулях.\nЦей кут нахилу мінливий.\nКожні 19 років вісь відхиляється від первісного положення і таким чином описує у просторі конус. Таке розгойдування осі називається\nнутацією.\nЗмінюється відносно до осі обертання і стану самої Землі. Про це свідчать переміщення географічних полюсів уздовж її поверхні, яке\nздійснювалося в усі часи\nіснування планети.\n\nНа рух нашої планети, в тому числі на швидкість обертання, впливають сили притягання Місяця і Сонця. Вони спричиняють утворення\nприпливів в океанах і у\nтвердій оболонці – земній корі, де амплітуда її підйому досягає 0,3 м.\n\nХарактер руху Землі по сонячній орбіті і навколо своєї осі визначає кількість сонячного тепла, що одержують різні ділянки планети.\nЦе впливає на хід\nгеологічних процесів. Наявність і характер осьового обертання планети визначають головні особливості її форми.");
        content2Scroll.setViewportView(jTextArea2);

        back.setBackground(new java.awt.Color(204, 0, 0));
        back.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        back.setText("Назад");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(content1Scroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(title))
                            .addComponent(content2Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(content1Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(content2Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(back)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        var generalInformation = new GeneralInformationView();
        generalInformation.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeaturesOfTheEarthsRotationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeaturesOfTheEarthsRotationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeaturesOfTheEarthsRotationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeaturesOfTheEarthsRotationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeaturesOfTheEarthsRotationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextArea content1;
    private javax.swing.JScrollPane content1Scroll;
    private javax.swing.JScrollPane content2Scroll;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
