/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javaatlas.Views;

import com.mycompany.javaatlas.MainForm;
import com.mycompany.javaatlas.Views.GeneralInformationAboutEarth.*;

/**
 *
 * @author user
 */
public class GeneralInformationView extends javax.swing.JFrame {
    private String _address;
    /**
     * Creates new form GeneralInformationView
     */
    public GeneralInformationView() {
        _address = new MainForm().getAddress();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        physicalSurfaceOfTheEarth = new javax.swing.JButton();
        shapeAndDimensionsOfTheEarth = new javax.swing.JButton();
        featuresOfTheEarthsRotation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        title.setText("Основні відомості про Землю");
        title.setToolTipText("Основні відомості");

        icon.setIcon(new javax.swing.ImageIcon(_address + "Images/General-info.gif"));

        back.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        back.setText("Назад");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        physicalSurfaceOfTheEarth.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        physicalSurfaceOfTheEarth.setText("Фізична поверхня Землі");
        physicalSurfaceOfTheEarth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicalSurfaceOfTheEarthActionPerformed(evt);
            }
        });

        shapeAndDimensionsOfTheEarth.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        shapeAndDimensionsOfTheEarth.setText("Форма і розміри Землі");
        shapeAndDimensionsOfTheEarth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shapeAndDimensionsOfTheEarthActionPerformed(evt);
            }
        });

        featuresOfTheEarthsRotation.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        featuresOfTheEarthsRotation.setText("Особливості обертання Землі");
        featuresOfTheEarthsRotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                featuresOfTheEarthsRotationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(title)
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(physicalSurfaceOfTheEarth, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shapeAndDimensionsOfTheEarth, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(featuresOfTheEarthsRotation, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(physicalSurfaceOfTheEarth)
                    .addComponent(shapeAndDimensionsOfTheEarth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(featuresOfTheEarthsRotation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(back)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainForm mainForm = new MainForm();
        mainForm.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void physicalSurfaceOfTheEarthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicalSurfaceOfTheEarthActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        var physicalSurfaceOfTheEarth = new PhysicalSurfaceOfTheEarthView();
        physicalSurfaceOfTheEarth.setVisible(true);
    }//GEN-LAST:event_physicalSurfaceOfTheEarthActionPerformed

    private void shapeAndDimensionsOfTheEarthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shapeAndDimensionsOfTheEarthActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        var shapeAndDimensionsOfTheEarth=new ShapeAndDimensionsOfTheEarthView();
        shapeAndDimensionsOfTheEarth.setVisible(true);
    }//GEN-LAST:event_shapeAndDimensionsOfTheEarthActionPerformed

    private void featuresOfTheEarthsRotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_featuresOfTheEarthsRotationActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        var featuresOfTheEarthsRotation = new FeaturesOfTheEarthsRotationView();
        featuresOfTheEarthsRotation.setVisible(true);
    }//GEN-LAST:event_featuresOfTheEarthsRotationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralInformationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton featuresOfTheEarthsRotation;
    private javax.swing.JLabel icon;
    private javax.swing.JButton physicalSurfaceOfTheEarth;
    private javax.swing.JButton shapeAndDimensionsOfTheEarth;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
